name: VyOS v1.4 Rolling Release

on:
  schedule:
    - cron: 0 3 * * *
  create:
  push:
  workflow_dispatch:
    inputs:
      prebuild_debug_enabled:
        type: boolean
        description: 'debug prebuild (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
      minisign_debug_enabled:
        type: boolean
        description: 'debug minisign (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
      release_debug_enabled:
        type: boolean
        description: 'debug release (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
  

env:
  BRANCH: current
  ARCHITECTURE: amd64
  BUILD_BY: vyos-build-action@github.com
  BUILD_TYPE: release
  VERSION: 1.4-rolling_bri
  DEBIAN_MIRROR: http://ftp.us.debian.org/debian/

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:current
      options: --workdir /vyos --privileged

    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Generate version string
      uses: haya14busa/action-cond@v1
      id: branch-filename
      with:
        cond: ${{ steps.branch-name.outputs.is_default == 'true' }}
        if_true: "${{ env.VERSION }}"
        if_false: "${{ env.VERSION }}_${{  steps.branch-name.outputs.current_branch  }}"
    - name: Set variables
      run: |
        export VERSION_BRANCH="${{ steps.branch-filename.outputs.value }}"
        echo "VERSION_BRANCH=${VERSION_BRANCH}" >> $GITHUB_ENV
        export VERSION_T=${VERSION_BRANCH}-$(date +%Y%m%d%H%M)
        export VERSION_L=${VERSION_BRANCH}-latest
        echo "VERSION_T=${VERSION_T}" >> $GITHUB_ENV
        echo "VERSION_L=${VERSION_L}" >> $GITHUB_ENV
        echo "ISO_T=vyos-${VERSION_T}-${ARCHITECTURE}.iso" >> $GITHUB_ENV
        echo "ISO_L=vyos-${VERSION_L}-${ARCHITECTURE}.iso" >> $GITHUB_ENV
        echo -----
        echo Now, my variables are:
        cat $GITHUB_ENV
        echo -----
      
    - name: Checkout vyos-build repo
      uses: actions/checkout@v3
      with:
        repository: vyos/vyos-build
        path: vyos-build
        
    - name: Checkout vyos-build-action repo
      uses: actions/checkout@v3
      with:
        path: vyos-build-action
        submodules: 'true'
    - name: prebuild tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ ( github.event_name == 'workflow_dispatch' && inputs.prebuild_debug_enabled ) }}     
    - name: Add minisign key
      env: 
        MINISIGN_PUBLIC_KEY: ${{ secrets.MINISIGN_PUBLIC_KEY }}
      run: |
        printenv MINISIGN_PUBLIC_KEY > vyos-build/data/live-build-config/includes.chroot/usr/share/vyos/keys/vyos-release.minisign.pub
    - name: Add Tailscale files #from vyos-tailscale/Makefile:prepare

      #working-directory: vyos-build-action/vyos-build-action
      run: |
        cp vyos-build-action/vyos-tailscale/tailscale/tailscale.gpg /tmp/tailscale.gpg

        mkdir -p vyos-build/data/live-build-config/includes.chroot/etc/default
        cp vyos-build-action/vyos-tailscale/tailscale/tailscaled vyos-build/data/live-build-config/includes.chroot/etc/default/tailscaled

        mkdir -p vyos-build/data/live-build-config/includes.chroot/etc/systemd/system/tailscaled.service.d
        cp vyos-build-action/vyos-tailscale/tailscale/override.conf vyos-build/data/live-build-config/includes.chroot/etc/systemd/system/tailscaled.service.d/override.conf
          
    - name: Add ZeroTier files
      run: |
        echo '-----BEGIN PGP PUBLIC KEY BLOCK-----' >/tmp/zt-gpg-key
        cat >>/tmp/zt-gpg-key << END_OF_KEY
        Comment: GPGTools - https://gpgtools.org

        mQINBFdQq7oBEADEVhyRiaL8dEjMPlI/idO8tA7adjhfvejxrJ3Axxi9YIuIKhWU
        5hNjDjZAiV9iSCMfJN3TjC3EDA+7nFyU6nDKeAMkXPbaPk7ti+Tb1nA4TJsBfBlm
        CC14aGWLItpp8sI00FUzorxLWRmU4kOkrRUJCq2kAMzbYWmHs0hHkWmvj8gGu6mJ
        WU3sDIjvdsm3hlgtqr9grPEnj+gA7xetGs3oIfp6YDKymGAV49HZmVAvSeoqfL1p
        pEKlNQ1aO9uNfHLdx6+4pS1miyo7D1s7ru2IcqhTDhg40cHTL/VldC3d8vXRFLIi
        Uo2tFZ6J1jyQP5c1K4rTpw3UNVne3ob7uCME+T1+ePeuM5Y/cpcCvAhJhO0rrlr0
        dP3lOKrVdZg4qhtFAspC85ivcuxWNWnfTOBrgnvxCA1fmBX+MLNUEDsuu55LBNQT
        5+WyrSchSlsczq+9EdomILhixUflDCShHs+Efvh7li6Pg56fwjEfj9DJYFhRvEvQ
        7GZ7xtysFzx4AYD4/g5kCDsMTbc9W4Jv+JrMt3JsXt2zqwI0P4R1cIAu0J6OZ4Xa
        dJ7Ci1WisQuJRcCUtBTUxcYAClNGeors5Nhl4zDrNIM7zIJp+GfPYdWKVSuW10mC
        r3OS9QctMSeVPX/KE85TexeRtmyd4zUdio49+WKgoBhM8Z9MpTaafn2OPQARAQAB
        tFBaZXJvVGllciwgSW5jLiAoWmVyb1RpZXIgU3VwcG9ydCBhbmQgUmVsZWFzZSBT
        aWduaW5nIEtleSkgPGNvbnRhY3RAemVyb3RpZXIuY29tPokCNwQTAQoAIQUCV1Cr
        ugIbAwULCQgHAwUVCgkICwUWAgMBAAIeAQIXgAAKCRAWVxmII+UqYViGEACnC3+3
        lRzfv7f7JLWo23FSHjlF3IiWfYd+47BLDx706SDih1H6Qt8CqRy706bWbtictEJ/
        xTaWgTEDzY/lRalYO5NAFTgK9h2zBP1t8zdEA/rmtVPOWOzd6jr0q3l3pKQTeMF0
        6g+uaMDG1OkBz6MCwdg9counz6oa8OHK76tXNIBEnGOPBW375z1O+ExyddQOHDcS
        IIsUlFmtIL1yBa7Q5NSfLofPLfS0/o2FItn0riSaAh866nXHynQemjTrqkUxf5On
        65RLM+AJQaEkX17vDlsSljHrtYLKrhEueqeq50e89c2Ya4ucmSVeC9lrSqfyvGOO
        P3aT/hrmeE9XBf7a9vozq7XhtViEC/ZSd1/z/oeypv4QYenfw8CtXP5bW1mKNK/M
        8xnrnYwo9BUMclX2ZAvu1rTyiUvGre9fEGfhlS0rjmCgYfMgBZ+R/bFGiNdn6gAd
        PSY/8fP8KFZl0xUzh2EnWe/bptoZ67CKkDbVZnfWtuKA0Ui7anitkjZiv+6wanv4
        +5A3k/H3D4JofIjRNgx/gdVPhJfWjAoutIgGeIWrkfcAP9EpsR5swyc4KuE6kJ/Y
        wXXVDQiju0xE1EdNx/S1UOeq0EHhOFqazuu00ojATekUPWenNjPWIjBYQ0Ag4ycL
        KU558PFLzqYaHphdWYgxfGR+XSgzVTN1r7lW87kCDQRXUKu6ARAA2wWOywNMzEiP
        ZK6CqLYGZqrpfx+drOxSowwfwjP3odcK8shR/3sxOmYVqZi0XVZtb9aJVz578rNb
        e4Vfugql1Yt6w3V84z/mtfj6ZbTOOU5yAGZQixm6fkXAnpG5Eer/C8Aw8dH1EreP
        Na1gIVcUzlpg2Ql23qjr5LqvGtUB4BqJSF4X8efNi/y0hj/GaivUMqCF6+Vvh3GG
        fhvzhgBPku/5wK2XwBL9BELqaQ/tWOXuztMw0xFH/De75IH3LIvQYCuv1pnM4hJL
        XYnpAGAWfmFtmXNnPVon6g542Z6c0G/qi657xA5vr6OSSbazDJXNiHXhgBYEzRrH
        napcohTQwFKEA3Q4iftrsTDX/eZVTrO9x6qKxwoBVTGwSE52InWAxkkcnZM6tkfV
        n7Ukc0oixZ6E70Svls27zFgaWbUFJQ6JFoC6h+5AYbaga6DwKCYOP3AR+q0ZkcH/
        oJIdvKuhF9zDZbQhd76b4gK3YXnMpVsj9sQ9P23gh61RkAQ1HIlGOBrHS/XYcvpk
        DcfIlJXKC3V1ggrG+BpKu46kiiYmRR1/yM0EXH2n99XhLNSxxFxxWhjyw8RcR6iG
        ovDxWAULW+bJHjaNJdgb8Kab7j2nT2odUjUHMP42uLJgvS5LgRn39IvtzjoScAqg
        8I817m8yLU/91D2f5qmJIwFI6ELwImkAEQEAAYkCHwQYAQoACQUCV1CrugIbDAAK
        CRAWVxmII+UqYWSSEACxaR/hhr8xUIXkIV52BeD+2BOS8FNOi0aM67L4fEVplrsV
        Op9fvAnUNmoiQo+RFdUdaD2Rpq+yUjQHHbj92mlk6Cmaon46wU+5bAWGYpV1Uf+o
        wbKw1Xv83Uj9uHo7zv9WDtOUXUiTe/S792icTfRYrKbwkfI8iCltgNhTQNX0lFX/
        Sr2y1/dGCTCMEuA/ClqGKCm9lIYdu+4z32V9VXTSX85DsUjLOCO/hl9SHaelJgmi
        IJzRY1XLbNDK4IH5eWtbaprkTNIGt00QhsnM5w+rn1tO80giSxXFpKBE+/pAx8PQ
        RdVFzxHtTUGMCkZcgOJolk8y+DJWtX8fP+3a4Vq11a3qKJ19VXk3qnuC1aeW7OQF
        j6ISyHsNNsnBw5BRaS5tdrpLXw6Z7TKr1eq+FylmoOK0pIw5xOdRmSVoFm4lVcI5
        e5EwB7IIRF00IFqrXe8dCT0oDT9RXc6CNh6GIs9D9YKwDPRD/NKQlYoegfa13Jz7
        S3RIXtOXudT1+A1kaBpGKnpXOYD3w7jW2l0zAd6a53AAGy4SnL1ac4cml76NIWiF
        m2KYzvMJZBk5dAtFa0SgLK4fg8X6Ygoo9E0JsXxSrW9I1JVfo6Ia//YOBMtt4XuN
        Awqahjkq87yxOYYTnJmr2OZtQuFboymfMhNqj3G2DYmZ/ZIXXPgwHx0fnd3R0Q==
        =JgAv
        END_OF_KEY
        echo '-----END PGP PUBLIC KEY BLOCK-----' >>/tmp/zt-gpg-key
        mkdir -p vyos-build/data/live-build-config/includes.chroot/etc/systemd/system/zerotier-one.service.d vyos-build/data/live-build-config/includes.chroot/var/lib/
        cp vyos-build-action/vyos-tailscale/tailscale/override.conf vyos-build/data/live-build-config/includes.chroot/etc/systemd/system/zerotier-one.service.d/override.conf
        mkdir -p /config/user-data/zerotier-one # this is a hack to prevent a file not found error https://github.com/b-/vyos-build-action/actions/runs/3853685758/jobs/6566902991#step:15:35
        ln -s /config/user-data/zerotier-one vyos-build/data/live-build-config/includes.chroot/var/lib/zerotier-one
        

    - name: Add /etc/ssh/ssh_config.d/00-default_key.conf file
      run: |
        mkdir -p vyos-build/data/live-build-config/includes.chroot/etc/ssh/ssh_config.d
        >'vyos-build/data/live-build-config/includes.chroot/etc/ssh/ssh_config.d/00-default_key.conf' cat<<EOF
        Host *
            IdentityFile /config/user-data/id_ed25519
        EOF
          
    - name: Add /etc/gitconfig
      run: |
        >'vyos-build/data/live-build-config/includes.chroot/etc/gitconfig' cat<<EOF
        [core]
                sshCommand = ssh -o StrictHostKeyChecking=no
        EOF
        
        
    - name: Add /etc/dhcp/dhclient-exit-hooks.d/99-run-user-hooks
      run: |
        set -x
        mkdir -p 'vyos-build/data/live-build-config/includes.chroot/etc/dhcp/dhclient-exit-hooks.d'
        >'vyos-build/data/live-build-config/includes.chroot/etc/dhcp/dhclient-exit-hooks.d/99-run-user-hooks' <<'EOF'
        #!/bin/bash
        #
        # Run user dhclient-exit-hooks
        DHCP_POST_HOOKS="/config/scripts/dhcp-client/post-hooks.d/"
        if [ -d "${DHCP_POST_HOOKS}" ] ; then
            run-parts "${DHCP_POST_HOOKS}"
        fi
        EOF
        chmod +x vyos-build/data/live-build-config/includes.chroot/etc/dhcp/dhclient-exit-hooks.d/99-run-user-hooks
    - name: prebuild tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ ( github.event_name == 'workflow_dispatch' && inputs.prebuild_debug_enabled ) }}      
    - name: Build ISO
      working-directory: vyos-build
      run: 
        sudo ./build-vyos-image iso 
          --architecture $ARCHITECTURE
          --build-by $BUILD_BY 
          --build-type $BUILD_TYPE 
          --version $VERSION_T
          --custom-apt-key /tmp/tailscale.gpg 
          --custom-apt-entry "deb https://pkgs.tailscale.com/stable/debian bullseye main" 
          --custom-package "tailscale" 
          --custom-apt-key /tmp/zt-gpg-key
          --custom-apt-entry "deb https://download.zerotier.com/debian/bullseye bullseye main"
          --custom-package "zerotier-one"
          --custom-package "git"
          --custom-package "vim"
          --custom-package "jq"
          --build-comment "bri's custom VyOS 1.4-rolling"
            
    - name: move into position 
      working-directory: ./vyos-build/build
      run: |
        pwd
        ls
        mkdir -vp /tmp/iso
        ln -vs $(pwd)/$ISO_T /tmp/iso/$ISO_T
        ln -vs $(pwd)/$ISO_T /tmp/iso/$ISO_L
    - name: install minisign private key
      env:
        MINISIGN_PRIVATE_KEY: ${{ secrets.MINISIGN_PRIVATE_KEY  }}
      run: |
        mkdir -p $HOME/.minisign
        printenv MINISIGN_PRIVATE_KEY  > $HOME/.minisign/minisign.key
    - name: minisign tmate session
      env:
        MINISIGN_PRIVATE_KEY: ${{ secrets.MINISIGN_PRIVATE_KEY  }}
      uses: mxschmitt/action-tmate@v3
      if: ${{ ( github.event_name == 'workflow_dispatch' && inputs.minisign_debug_enabled ) }}
    - name: build libsodium
      run: |
        cd /tmp
        curl -L https://download.libsodium.org/libsodium/releases/LATEST.tar.gz | tar -zxv
        cd libsodium-stable
        ./configure && make -j4 && make install
    - name: clone minisign
      uses: actions/checkout@v3
      with:
        repository: jedisct1/minisign
        path: minisign
    - name: build minisign
      working-directory: minisign
      run: |
        mkdir -p build
        cd build
        cmake ..
        make -j4 && make install
        
    - name: sign build artifacts
      run: |
        cd /tmp/iso
        set +o pipefail
        echo | minisign -Sm /tmp/iso/*
        set -o pipefail

    - name: pre-release tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ ( github.event_name == 'workflow_dispatch' && inputs.minisign_debug_enabled ) }}
    - name: build libsodium
      run: |
        cd /tmp
        curl -L https://download.libsodium.org/libsodium/releases/LATEST.tar.gz | tar -zxv
        cd libsodium-stable
        ./configure && make -j4 && make install
       
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{  env.VERSION_BRANCH  }}
        files: "/tmp/iso/*"
                    
            
  delete_old_workflow_runs:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Delete old workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 31
